---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat_cop.tower_configuration
    - ansible.tower
  pre_tasks:

    - name: "Load tower objects from tower_objects.yml"
      include_vars:
        file: "tower_objects.yml"
      failed_when: false
      tags:
        - always

    - name: "Load tower objects from tower_objects.d/*"
      include_vars:
        dir: "tower_objects.d"
      failed_when: false
      tags:
        - always

  roles:
    - {role: tower_settings, when: tower_settings is defined, tags: tower_settings}
    - {role: credentials, when: tower_credentials is defined, tags: credentials}
    - {role: projects, when: tower_projects is defined, tags: projects}
    - {role: inventories, when: tower_inventories is defined, tags: inventories}
    - {role: inventory_sources, when: tower_inventory_sources is defined, tags: inventory_sources}
    - {role: job_templates, when: tower_templates is defined, tags: job_templates}
    - {role: workflow_job_templates, when: tower_workflows is defined, tags: workflow_job_templates}
    # etc.
...
