---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat_cop.tower_configuration
    - ansible.tower
  pre_tasks:

    - name: "Load tower objects from tower_objects.yml"
      include_vars:
        file: "tower_objects.yml"
      failed_when: false

    - name: "Load tower objects from tower_objects.d/*"
      include_vars:
        dir: "tower_objects.d"
      failed_when: false

  roles:
    - credentials
    - projects
    - inventory_sources
    - inventories
    - job_templates
    - workflow_job_templates
    # etc.
...