---
# yamllint disable rule:line-length

image: quay.io/anestero/cicd-ansible:ansible29-latest
# For newer versions of AWX/AAP use the latest (ansible 2.11) image
# image: quay.io/anestero/cicd-ansible:latest


stages:
  - lint
  - controller_configuration


lint:
  interruptible: true
  stage: lint
  rules:
    # Run for detached Merge Request pipelines
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    # Run on non-default branches, e.g. feature- fix- or devel- branches
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: always
  script:
    - yamllint $(find . -name '*.y*ml'| xargs)


controller_configuration:
  stage: controller_configuration
  rules:
    # Do not run for Merge Requests
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    # Make real changes on the Controller only via default branch
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
  variables:
    GIT_USERNAME: ''                 # Override with GitLab's masked/protected CICD vars
    GIT_PASSWORD: ''                 # Override with GitLab's masked/protected CICD vars
    CONTROLLER_HOST: ''              # Override with GitLab's CICD vars
    CONTROLLER_USERNAME: ''          # Override with GitLab's CICD masked/protected vars
    CONTROLLER_PASSWORD: ''          # Override with GitLab's CICD masked/protected vars
    CONTROLLER_VERIFY_SSL: ''        # Override with GitLab's CICD vars, defaults to true
    ANSIBLE_FORCE_COLOR: 'true'
    ANSIBLE_HOST_KEY_CHECKING: 'false'
  before_script:
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    # Inject values from GitLab CI/CD vars
    - mkdir -p /tmp/configs/controller_configs.d ./configs
    - for f in controller_configs.yml controller_configs.d/*; do [[ -f ${f} ]] && cat ${f} | envsubst > /tmp/configs/${f}; done
    # Merge all configs into one file
    # in case the same assets appear in different files
    # e.g. "controller_settings" for ldap and jobs are in ldap_settings.yml and jobs_settings.yml
    - yaml-merge $(find /tmp/configs -type f --output configs/merged_config.yml)
    - export CONTROLLER_CONFIGS_DIR=${PWD}/configs
  script:
    - ansible-playbook ~/.ansible/collections/ansible_collections/redhat_cop/controller_configuration/playbooks/configure_controller.yml
    # For newer versions of AWX/AAP that run ansible 2.11 call the playbook from its namespace
    # - ansible-playbook redhat_cop.controller_configuration.configure_controller


# yamllint enable rule:line-length
