ensure_tower_objects:
  image: quay.io/anestero/cicd-ansible:v0.1
  variables:
    HELPERS_REVISION: main
    HELPERS_REPO: github.com/nesanton/ansible_tower_gitops.git
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'
  before_script:
    - git clone https://${HELPERS_TOKEN}@${HELPERS_REPO} helpers
    - cd helpers && git checkout ${HELPERS_REVISION} && cd ..
    - mv helpers/* ./ && rm -rf helpers
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    # Inject secrets from GitLab CI/CD vars
    - cat tower_objects.yml | envsubst > tower_objects.tmp && mv tower_objects.tmp tower_objects.yml
  script:
    - ansible-playbook ensure_tower_objects.yml


