---  
controller_projects:
  - name: example_inventory_source_project
    organization: Default
    scm_url: ${SCM_URL}
    scm_branch: ${SCM_BRANCH}
    scm_type: git
    scm_clean: false
    scm_delete_on_update: false
    scm_update_on_launch: true
    credential: git_auth
    allow_override: false

controller_inventory_sources:
  - name: example_inventory_source
    source: scm
    source_path: inventory.ini
    source_project: example_inventory_source_project
    inventory: example_inventory
    overwrite: true
    overwrite_vars: true
    update_on_launch: false
    update_on_project_update: true

controller_inventories:
  - name: example_inventory
    organization: Default
    instance_groups: []
...

