name: Build images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Quay.io
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          IMAGE_REGISTRY: quay.io
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
    
      - name: Checkout the Repo
        uses: actions/checkout@v2

      - name: Source vars
        run: |
          cat ${GITHUB_WORKSPACE}/container_images/buildah/cicd_ansible.bash | grep -Po '\K^[A-Z_]*\=.*' | cut -d'#' -f1 >> ${GITHUB_ENV}

      - name: Build the image
        run: bash ${GITHUB_WORKSPACE}/container_images/buildah/cicd_ansible.bash
        
      - name: debug image names
        run: |
          podman images
          buildah images
          echo $IMAGE
          echo $VERSION

      - name: Push to quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${IMAGE}
          tags: ${VERSION} latest
          registry: quay.io/anestero/

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
